### ISSUE TITLE
Users Submit Media (Create Post)

### ISSUE THREAD

**Issue by ASOUDRY** [052223-java-angular/Flumbr-Frontend#4]
Description:
Implement UI to handle the upload of various media content types to the repository

Acceptance Criteria:
UI can handle the following media content types:
- Short messages
- Images 
- Videos
- Long Messages

In addition to the content, the data sent to the server must contain
- The content poster
- Tags

SP: 2

**Comment by tgj** [comment]
Pretty much done, just need to send tags to backend

**Comment by tgj** [comment]
Need to fix an error:

`VM9:1 ERROR TypeError: Cannot read properties of null (reading 'match')`
